# Generated by Django 5.0.1 on 2024-01-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
