# Generated by Django 4.2.9 on 2024-01-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='thebook',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='accounts.book'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='lender',
            field=models.CharField(max_length=50),
        ),
    ]
